//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(identifier: "com.Ray.CoreAnimation-Collection") ?? Bundle.main
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 color palettes.
  struct color {
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 3 files.
  struct file {
    /// Resource file `Ship.mp4`.
    static let shipMp4 = Rswift.FileResource(bundle: R.hostingBundle, name: "Ship", pathExtension: "mp4")
    /// Resource file `Vacation Photos`.
    static let vacationPhotos = Rswift.FileResource(bundle: R.hostingBundle, name: "Vacation Photos", pathExtension: "")
    /// Resource file `tile_floor.png`.
    static let tile_floorPng = Rswift.FileResource(bundle: R.hostingBundle, name: "tile_floor", pathExtension: "png")
    
    /// `bundle.url(forResource: "Ship", withExtension: "mp4")`
    static func shipMp4(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.shipMp4
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Vacation Photos", withExtension: "")`
    static func vacationPhotos(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.vacationPhotos
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "tile_floor", withExtension: "png")`
    static func tile_floorPng(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.tile_floorPng
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 96 images.
  struct image {
    /// Image `Anchor`.
    static let anchor = Rswift.ImageResource(bundle: R.hostingBundle, name: "Anchor")
    /// Image `Ball`.
    static let ball = Rswift.ImageResource(bundle: R.hostingBundle, name: "Ball")
    /// Image `BigSnowman`.
    static let bigSnowman = Rswift.ImageResource(bundle: R.hostingBundle, name: "BigSnowman")
    /// Image `Button`.
    static let button = Rswift.ImageResource(bundle: R.hostingBundle, name: "Button")
    /// Image `Chalk`.
    static let chalk = Rswift.ImageResource(bundle: R.hostingBundle, name: "Chalk")
    /// Image `ClockFace`.
    static let clockFace = Rswift.ImageResource(bundle: R.hostingBundle, name: "ClockFace")
    /// Image `Cone`.
    static let cone = Rswift.ImageResource(bundle: R.hostingBundle, name: "Cone")
    /// Image `Digits`.
    static let digits = Rswift.ImageResource(bundle: R.hostingBundle, name: "Digits")
    /// Image `Door`.
    static let door = Rswift.ImageResource(bundle: R.hostingBundle, name: "Door")
    /// Image `HourHand`.
    static let hourHand = Rswift.ImageResource(bundle: R.hostingBundle, name: "HourHand")
    /// Image `Igloo`.
    static let igloo = Rswift.ImageResource(bundle: R.hostingBundle, name: "Igloo")
    /// Image `MinuteHand`.
    static let minuteHand = Rswift.ImageResource(bundle: R.hostingBundle, name: "MinuteHand")
    /// Image `Rounded`.
    static let rounded = Rswift.ImageResource(bundle: R.hostingBundle, name: "Rounded")
    /// Image `SecondHand`.
    static let secondHand = Rswift.ImageResource(bundle: R.hostingBundle, name: "SecondHand")
    /// Image `Ship`.
    static let ship = Rswift.ImageResource(bundle: R.hostingBundle, name: "Ship")
    /// Image `Snowman_00_00`.
    static let snowman_00_00 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_00_00")
    /// Image `Snowman_00_01`.
    static let snowman_00_01 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_00_01")
    /// Image `Snowman_00_02`.
    static let snowman_00_02 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_00_02")
    /// Image `Snowman_00_03`.
    static let snowman_00_03 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_00_03")
    /// Image `Snowman_00_04`.
    static let snowman_00_04 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_00_04")
    /// Image `Snowman_00_05`.
    static let snowman_00_05 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_00_05")
    /// Image `Snowman_00_06`.
    static let snowman_00_06 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_00_06")
    /// Image `Snowman_00_07`.
    static let snowman_00_07 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_00_07")
    /// Image `Snowman_01_00`.
    static let snowman_01_00 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_01_00")
    /// Image `Snowman_01_01`.
    static let snowman_01_01 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_01_01")
    /// Image `Snowman_01_02`.
    static let snowman_01_02 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_01_02")
    /// Image `Snowman_01_03`.
    static let snowman_01_03 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_01_03")
    /// Image `Snowman_01_04`.
    static let snowman_01_04 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_01_04")
    /// Image `Snowman_01_05`.
    static let snowman_01_05 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_01_05")
    /// Image `Snowman_01_06`.
    static let snowman_01_06 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_01_06")
    /// Image `Snowman_01_07`.
    static let snowman_01_07 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_01_07")
    /// Image `Snowman_02_00`.
    static let snowman_02_00 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_02_00")
    /// Image `Snowman_02_01`.
    static let snowman_02_01 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_02_01")
    /// Image `Snowman_02_02`.
    static let snowman_02_02 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_02_02")
    /// Image `Snowman_02_03`.
    static let snowman_02_03 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_02_03")
    /// Image `Snowman_02_04`.
    static let snowman_02_04 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_02_04")
    /// Image `Snowman_02_05`.
    static let snowman_02_05 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_02_05")
    /// Image `Snowman_02_06`.
    static let snowman_02_06 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_02_06")
    /// Image `Snowman_02_07`.
    static let snowman_02_07 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_02_07")
    /// Image `Snowman_03_00`.
    static let snowman_03_00 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_03_00")
    /// Image `Snowman_03_01`.
    static let snowman_03_01 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_03_01")
    /// Image `Snowman_03_02`.
    static let snowman_03_02 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_03_02")
    /// Image `Snowman_03_03`.
    static let snowman_03_03 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_03_03")
    /// Image `Snowman_03_04`.
    static let snowman_03_04 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_03_04")
    /// Image `Snowman_03_05`.
    static let snowman_03_05 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_03_05")
    /// Image `Snowman_03_06`.
    static let snowman_03_06 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_03_06")
    /// Image `Snowman_03_07`.
    static let snowman_03_07 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_03_07")
    /// Image `Snowman_04_00`.
    static let snowman_04_00 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_04_00")
    /// Image `Snowman_04_01`.
    static let snowman_04_01 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_04_01")
    /// Image `Snowman_04_02`.
    static let snowman_04_02 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_04_02")
    /// Image `Snowman_04_03`.
    static let snowman_04_03 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_04_03")
    /// Image `Snowman_04_04`.
    static let snowman_04_04 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_04_04")
    /// Image `Snowman_04_05`.
    static let snowman_04_05 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_04_05")
    /// Image `Snowman_04_06`.
    static let snowman_04_06 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_04_06")
    /// Image `Snowman_04_07`.
    static let snowman_04_07 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_04_07")
    /// Image `Snowman_05_00`.
    static let snowman_05_00 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_05_00")
    /// Image `Snowman_05_01`.
    static let snowman_05_01 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_05_01")
    /// Image `Snowman_05_02`.
    static let snowman_05_02 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_05_02")
    /// Image `Snowman_05_03`.
    static let snowman_05_03 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_05_03")
    /// Image `Snowman_05_04`.
    static let snowman_05_04 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_05_04")
    /// Image `Snowman_05_05`.
    static let snowman_05_05 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_05_05")
    /// Image `Snowman_05_06`.
    static let snowman_05_06 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_05_06")
    /// Image `Snowman_05_07`.
    static let snowman_05_07 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_05_07")
    /// Image `Snowman_06_00`.
    static let snowman_06_00 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_06_00")
    /// Image `Snowman_06_01`.
    static let snowman_06_01 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_06_01")
    /// Image `Snowman_06_02`.
    static let snowman_06_02 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_06_02")
    /// Image `Snowman_06_03`.
    static let snowman_06_03 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_06_03")
    /// Image `Snowman_06_04`.
    static let snowman_06_04 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_06_04")
    /// Image `Snowman_06_05`.
    static let snowman_06_05 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_06_05")
    /// Image `Snowman_06_06`.
    static let snowman_06_06 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_06_06")
    /// Image `Snowman_06_07`.
    static let snowman_06_07 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_06_07")
    /// Image `Snowman_07_00`.
    static let snowman_07_00 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_07_00")
    /// Image `Snowman_07_01`.
    static let snowman_07_01 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_07_01")
    /// Image `Snowman_07_02`.
    static let snowman_07_02 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_07_02")
    /// Image `Snowman_07_03`.
    static let snowman_07_03 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_07_03")
    /// Image `Snowman_07_04`.
    static let snowman_07_04 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_07_04")
    /// Image `Snowman_07_05`.
    static let snowman_07_05 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_07_05")
    /// Image `Snowman_07_06`.
    static let snowman_07_06 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_07_06")
    /// Image `Snowman_07_07`.
    static let snowman_07_07 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman_07_07")
    /// Image `Snowman`.
    static let snowman = Rswift.ImageResource(bundle: R.hostingBundle, name: "Snowman")
    /// Image `Spaceship`.
    static let spaceship = Rswift.ImageResource(bundle: R.hostingBundle, name: "Spaceship")
    /// Image `Spark`.
    static let spark = Rswift.ImageResource(bundle: R.hostingBundle, name: "Spark")
    /// Image `Sprites`.
    static let sprites = Rswift.ImageResource(bundle: R.hostingBundle, name: "Sprites")
    /// Image `clock_highlight`.
    static let clock_highlight = Rswift.ImageResource(bundle: R.hostingBundle, name: "clock_highlight")
    /// Image `clock`.
    static let clock = Rswift.ImageResource(bundle: R.hostingBundle, name: "clock")
    /// Image `juice_highlight`.
    static let juice_highlight = Rswift.ImageResource(bundle: R.hostingBundle, name: "juice_highlight")
    /// Image `juice`.
    static let juice = Rswift.ImageResource(bundle: R.hostingBundle, name: "juice")
    /// Image `pencil_highlight`.
    static let pencil_highlight = Rswift.ImageResource(bundle: R.hostingBundle, name: "pencil_highlight")
    /// Image `pencil`.
    static let pencil = Rswift.ImageResource(bundle: R.hostingBundle, name: "pencil")
    /// Image `powerButton_highlight`.
    static let powerButton_highlight = Rswift.ImageResource(bundle: R.hostingBundle, name: "powerButton_highlight")
    /// Image `powerButton`.
    static let powerButton = Rswift.ImageResource(bundle: R.hostingBundle, name: "powerButton")
    /// Image `service_highlight`.
    static let service_highlight = Rswift.ImageResource(bundle: R.hostingBundle, name: "service_highlight")
    /// Image `service`.
    static let service = Rswift.ImageResource(bundle: R.hostingBundle, name: "service")
    /// Image `shower_highlight`.
    static let shower_highlight = Rswift.ImageResource(bundle: R.hostingBundle, name: "shower_highlight")
    /// Image `shower`.
    static let shower = Rswift.ImageResource(bundle: R.hostingBundle, name: "shower")
    /// Image `tile_floor`.
    static let tile_floor = Rswift.ImageResource(bundle: R.hostingBundle, name: "tile_floor")
    
    /// `UIImage(named: "Anchor", bundle: ..., traitCollection: ...)`
    static func anchor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.anchor, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Ball", bundle: ..., traitCollection: ...)`
    static func ball(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ball, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "BigSnowman", bundle: ..., traitCollection: ...)`
    static func bigSnowman(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.bigSnowman, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Button", bundle: ..., traitCollection: ...)`
    static func button(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.button, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Chalk", bundle: ..., traitCollection: ...)`
    static func chalk(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.chalk, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ClockFace", bundle: ..., traitCollection: ...)`
    static func clockFace(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.clockFace, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Cone", bundle: ..., traitCollection: ...)`
    static func cone(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.cone, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Digits", bundle: ..., traitCollection: ...)`
    static func digits(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.digits, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Door", bundle: ..., traitCollection: ...)`
    static func door(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.door, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "HourHand", bundle: ..., traitCollection: ...)`
    static func hourHand(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.hourHand, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Igloo", bundle: ..., traitCollection: ...)`
    static func igloo(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.igloo, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "MinuteHand", bundle: ..., traitCollection: ...)`
    static func minuteHand(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.minuteHand, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Rounded", bundle: ..., traitCollection: ...)`
    static func rounded(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.rounded, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "SecondHand", bundle: ..., traitCollection: ...)`
    static func secondHand(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.secondHand, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Ship", bundle: ..., traitCollection: ...)`
    static func ship(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ship, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman", bundle: ..., traitCollection: ...)`
    static func snowman(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_00_00", bundle: ..., traitCollection: ...)`
    static func snowman_00_00(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_00_00, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_00_01", bundle: ..., traitCollection: ...)`
    static func snowman_00_01(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_00_01, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_00_02", bundle: ..., traitCollection: ...)`
    static func snowman_00_02(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_00_02, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_00_03", bundle: ..., traitCollection: ...)`
    static func snowman_00_03(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_00_03, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_00_04", bundle: ..., traitCollection: ...)`
    static func snowman_00_04(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_00_04, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_00_05", bundle: ..., traitCollection: ...)`
    static func snowman_00_05(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_00_05, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_00_06", bundle: ..., traitCollection: ...)`
    static func snowman_00_06(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_00_06, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_00_07", bundle: ..., traitCollection: ...)`
    static func snowman_00_07(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_00_07, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_01_00", bundle: ..., traitCollection: ...)`
    static func snowman_01_00(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_01_00, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_01_01", bundle: ..., traitCollection: ...)`
    static func snowman_01_01(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_01_01, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_01_02", bundle: ..., traitCollection: ...)`
    static func snowman_01_02(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_01_02, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_01_03", bundle: ..., traitCollection: ...)`
    static func snowman_01_03(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_01_03, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_01_04", bundle: ..., traitCollection: ...)`
    static func snowman_01_04(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_01_04, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_01_05", bundle: ..., traitCollection: ...)`
    static func snowman_01_05(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_01_05, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_01_06", bundle: ..., traitCollection: ...)`
    static func snowman_01_06(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_01_06, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_01_07", bundle: ..., traitCollection: ...)`
    static func snowman_01_07(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_01_07, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_02_00", bundle: ..., traitCollection: ...)`
    static func snowman_02_00(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_02_00, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_02_01", bundle: ..., traitCollection: ...)`
    static func snowman_02_01(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_02_01, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_02_02", bundle: ..., traitCollection: ...)`
    static func snowman_02_02(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_02_02, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_02_03", bundle: ..., traitCollection: ...)`
    static func snowman_02_03(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_02_03, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_02_04", bundle: ..., traitCollection: ...)`
    static func snowman_02_04(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_02_04, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_02_05", bundle: ..., traitCollection: ...)`
    static func snowman_02_05(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_02_05, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_02_06", bundle: ..., traitCollection: ...)`
    static func snowman_02_06(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_02_06, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_02_07", bundle: ..., traitCollection: ...)`
    static func snowman_02_07(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_02_07, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_03_00", bundle: ..., traitCollection: ...)`
    static func snowman_03_00(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_03_00, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_03_01", bundle: ..., traitCollection: ...)`
    static func snowman_03_01(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_03_01, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_03_02", bundle: ..., traitCollection: ...)`
    static func snowman_03_02(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_03_02, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_03_03", bundle: ..., traitCollection: ...)`
    static func snowman_03_03(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_03_03, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_03_04", bundle: ..., traitCollection: ...)`
    static func snowman_03_04(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_03_04, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_03_05", bundle: ..., traitCollection: ...)`
    static func snowman_03_05(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_03_05, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_03_06", bundle: ..., traitCollection: ...)`
    static func snowman_03_06(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_03_06, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_03_07", bundle: ..., traitCollection: ...)`
    static func snowman_03_07(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_03_07, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_04_00", bundle: ..., traitCollection: ...)`
    static func snowman_04_00(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_04_00, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_04_01", bundle: ..., traitCollection: ...)`
    static func snowman_04_01(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_04_01, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_04_02", bundle: ..., traitCollection: ...)`
    static func snowman_04_02(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_04_02, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_04_03", bundle: ..., traitCollection: ...)`
    static func snowman_04_03(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_04_03, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_04_04", bundle: ..., traitCollection: ...)`
    static func snowman_04_04(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_04_04, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_04_05", bundle: ..., traitCollection: ...)`
    static func snowman_04_05(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_04_05, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_04_06", bundle: ..., traitCollection: ...)`
    static func snowman_04_06(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_04_06, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_04_07", bundle: ..., traitCollection: ...)`
    static func snowman_04_07(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_04_07, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_05_00", bundle: ..., traitCollection: ...)`
    static func snowman_05_00(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_05_00, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_05_01", bundle: ..., traitCollection: ...)`
    static func snowman_05_01(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_05_01, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_05_02", bundle: ..., traitCollection: ...)`
    static func snowman_05_02(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_05_02, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_05_03", bundle: ..., traitCollection: ...)`
    static func snowman_05_03(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_05_03, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_05_04", bundle: ..., traitCollection: ...)`
    static func snowman_05_04(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_05_04, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_05_05", bundle: ..., traitCollection: ...)`
    static func snowman_05_05(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_05_05, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_05_06", bundle: ..., traitCollection: ...)`
    static func snowman_05_06(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_05_06, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_05_07", bundle: ..., traitCollection: ...)`
    static func snowman_05_07(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_05_07, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_06_00", bundle: ..., traitCollection: ...)`
    static func snowman_06_00(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_06_00, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_06_01", bundle: ..., traitCollection: ...)`
    static func snowman_06_01(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_06_01, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_06_02", bundle: ..., traitCollection: ...)`
    static func snowman_06_02(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_06_02, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_06_03", bundle: ..., traitCollection: ...)`
    static func snowman_06_03(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_06_03, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_06_04", bundle: ..., traitCollection: ...)`
    static func snowman_06_04(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_06_04, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_06_05", bundle: ..., traitCollection: ...)`
    static func snowman_06_05(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_06_05, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_06_06", bundle: ..., traitCollection: ...)`
    static func snowman_06_06(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_06_06, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_06_07", bundle: ..., traitCollection: ...)`
    static func snowman_06_07(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_06_07, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_07_00", bundle: ..., traitCollection: ...)`
    static func snowman_07_00(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_07_00, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_07_01", bundle: ..., traitCollection: ...)`
    static func snowman_07_01(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_07_01, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_07_02", bundle: ..., traitCollection: ...)`
    static func snowman_07_02(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_07_02, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_07_03", bundle: ..., traitCollection: ...)`
    static func snowman_07_03(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_07_03, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_07_04", bundle: ..., traitCollection: ...)`
    static func snowman_07_04(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_07_04, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_07_05", bundle: ..., traitCollection: ...)`
    static func snowman_07_05(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_07_05, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_07_06", bundle: ..., traitCollection: ...)`
    static func snowman_07_06(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_07_06, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Snowman_07_07", bundle: ..., traitCollection: ...)`
    static func snowman_07_07(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.snowman_07_07, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Spaceship", bundle: ..., traitCollection: ...)`
    static func spaceship(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.spaceship, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Spark", bundle: ..., traitCollection: ...)`
    static func spark(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.spark, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Sprites", bundle: ..., traitCollection: ...)`
    static func sprites(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.sprites, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "clock", bundle: ..., traitCollection: ...)`
    static func clock(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.clock, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "clock_highlight", bundle: ..., traitCollection: ...)`
    static func clock_highlight(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.clock_highlight, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "juice", bundle: ..., traitCollection: ...)`
    static func juice(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.juice, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "juice_highlight", bundle: ..., traitCollection: ...)`
    static func juice_highlight(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.juice_highlight, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "pencil", bundle: ..., traitCollection: ...)`
    static func pencil(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.pencil, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "pencil_highlight", bundle: ..., traitCollection: ...)`
    static func pencil_highlight(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.pencil_highlight, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "powerButton", bundle: ..., traitCollection: ...)`
    static func powerButton(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.powerButton, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "powerButton_highlight", bundle: ..., traitCollection: ...)`
    static func powerButton_highlight(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.powerButton_highlight, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "service", bundle: ..., traitCollection: ...)`
    static func service(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.service, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "service_highlight", bundle: ..., traitCollection: ...)`
    static func service_highlight(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.service_highlight, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "shower", bundle: ..., traitCollection: ...)`
    static func shower(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.shower, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "shower_highlight", bundle: ..., traitCollection: ...)`
    static func shower_highlight(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.shower_highlight, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tile_floor", bundle: ..., traitCollection: ...)`
    static func tile_floor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tile_floor, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 1 nibs.
  struct nib {
    /// Nib `SwitchersCollectionViewController`.
    static let switchersCollectionViewController = _R.nib._SwitchersCollectionViewController()
    
    /// `UINib(name: "SwitchersCollectionViewController", in: bundle)`
    static func switchersCollectionViewController(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.switchersCollectionViewController)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 0 reuse identifiers.
  struct reuseIdentifier {
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 0 view controllers.
  struct segue {
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 0 localization tables.
  struct string {
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      // There are no resources to validate
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}

struct _R {
  struct nib {
    struct _SwitchersCollectionViewController: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "SwitchersCollectionViewController"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]? = nil) -> UIKit.UIView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  struct storyboard {
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}